package jobs

import (
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"strings"
	"time"
)

var (
	// ErrInvalidKind indicates that a submission did not specify an executor.
	ErrInvalidKind = errors.New("job kind is required")
	// ErrInvalidPayload indicates that the job payload is not valid JSON.
	ErrInvalidPayload = errors.New("job payload must be valid JSON")
	// ErrInvalidID indicates that a request did not provide a canonical UUID.
	ErrInvalidID = errors.New("job ID must be a UUID")
	// ErrNotFound indicates that no persisted job has the requested ID.
	ErrNotFound = errors.New("job not found")
	// ErrNotRunning indicates that a worker attempted a terminal update for a
	// job whose durable state is no longer RUNNING.
	ErrNotRunning = errors.New("job is not running")
)

var canonicalUUID = regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`)

// Status describes the durable lifecycle of a job.
type Status string

const (
	StatusQueued    Status = "QUEUED"
	StatusRunning   Status = "RUNNING"
	StatusSucceeded Status = "SUCCEEDED"
	StatusFailed    Status = "FAILED"
)

// Job is one independently executable unit of work.
//
// Kind selects an executor in a later increment. Payload is executor-specific
// JSON, deliberately kept opaque to the scheduler's core.
type Job struct {
	ID           string          `json:"id"`
	Kind         string          `json:"kind"`
	Payload      json.RawMessage `json:"payload"`
	Status       Status          `json:"status"`
	ErrorMessage *string         `json:"error_message,omitempty"`
	CreatedAt    time.Time       `json:"created_at"`
	StartedAt    *time.Time      `json:"started_at,omitempty"`
	CompletedAt  *time.Time      `json:"completed_at,omitempty"`
}

// New creates a queued job that is ready for a worker to claim.
func New(kind string, payload json.RawMessage, now time.Time) (Job, error) {
	if strings.TrimSpace(kind) == "" {
		return Job{}, ErrInvalidKind
	}

	if len(payload) == 0 {
		payload = json.RawMessage(`{}`)
	}
	if !json.Valid(payload) {
		return Job{}, ErrInvalidPayload
	}

	return Job{
		Kind:      kind,
		Payload:   payload,
		Status:    StatusQueued,
		CreatedAt: now.UTC(),
	}, nil
}

// ValidateID verifies that id uses the UUID format generated by PostgreSQL.
func ValidateID(id string) error {
	if !canonicalUUID.MatchString(id) {
		return ErrInvalidID
	}
	return nil
}

// Start records that a worker began executing a queued job.
func (j *Job) Start(now time.Time) error {
	if j.Status != StatusQueued {
		return fmt.Errorf("cannot start job in %s state", j.Status)
	}

	startedAt := now.UTC()
	j.Status = StatusRunning
	j.StartedAt = &startedAt
	return nil
}

// Succeed records successful completion of a running job.
func (j *Job) Succeed(now time.Time) error {
	if j.Status != StatusRunning {
		return fmt.Errorf("cannot succeed job in %s state", j.Status)
	}

	completedAt := now.UTC()
	j.Status = StatusSucceeded
	j.CompletedAt = &completedAt
	j.ErrorMessage = nil
	return nil
}

// Fail records an execution failure for a running job.
func (j *Job) Fail(message string, now time.Time) error {
	if j.Status != StatusRunning {
		return fmt.Errorf("cannot fail job in %s state", j.Status)
	}
	if strings.TrimSpace(message) == "" {
		return fmt.Errorf("failure message is required")
	}

	completedAt := now.UTC()
	j.Status = StatusFailed
	j.CompletedAt = &completedAt
	j.ErrorMessage = &message
	return nil
}
